Deploy
moonshotcollective/scaffold-directory pull request #64
Opened 2021-09-30 10:30 UTC by carletex

**Backend**: (Manually) Deployed successfully to App Engine. We could add Cloud Build for CD.
**Frontend**: Will use netlify

2021-09-30 10:39 UTC, carletex commented
Hey @over9001 Did you get a Netlify request? I need it to be able to deploy this repo's frontend to Netlify.

![image](https://user-images.githubusercontent.com/2486142/135440420-a8a30e84-fa15-481a-b685-c38dcc8a4205.png)

2021-10-01 10:17 UTC, sogasg requested changes
Nice work :) 

I got it running both locally and with the Firebase DB. However, I did not manage to do the Firebase setup solely based on the information in the readme. I suggested some updates.

Also, I did not test the deployment to the Google app engine only ran it locally.

2021-10-01 10:17 UTC, sogasg commented on README.md
> +If you want to use Firebase (firestore) for data storage, you'll need to create a Firebase project and download the service account key configuration. You can generate and download the file at <https
```suggestion
If you want to use Firebase (firestore) for data storage, you'll need to create a Firebase project and download the service account key configuration. You can generate and download the service account file at <https://console.cloud.google.com/> by 1.) select your Firebase project, 2.) go to IAM & Admin > Service Accounts, 3.) create a service account or click one that is already created, 4.) go to keys of that account, and 5.) Add Key > Create key and select a JSON key type.
```

2021-10-01 10:17 UTC, sogasg commented on README.md
> +Then you will have to create a `.env` file in `packages/backend/` with `DATABASE_SERVICE=firebase` the path to the service account on `GOOGLE_APPLICATION_CREDENTIALS` (see a sample here `packages/bac
```suggestion
Then you will have to create a `.env` file in `packages/backend/` with `DATABASE_SERVICE=firebase` and add the full path to the service account file in `GOOGLE_APPLICATION_CREDENTIALS` (see a sample here `packages/backend/.env.sample`).
```

2021-10-01 10:31 UTC, carletex commented
Thanks @sogasg !! Accepted your changes, I think it's clear now.

> Also, I did not test the deployment to the Google app engine only ran it locally.

Yep, hard to test unless you create a project yourself. This front-end https://wonderful-kirch-4ab41a.netlify.app/ is making requests to the GApp Engine backend.

2021-10-01 10:33 UTC, sogasg approved these changes
Nice 😄

2021-10-01 10:33 UTC, merged